In [3]:
import pandas as pd
import numpy as np
import requests
from io import StringIO

In [11]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome'}

response = requests.get(url, headers=headers)
tables = pd.read_html(StringIO(response.text))

sp500 = tables[0]

In [31]:
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [49]:
#Creating the required Dataframe.

df1 = sp500[['Symbol', 'Security', 'Date added']]
df1

    Symbol             Security  Date added
0      MMM                   3M  1957-03-04
1      AOS          A. O. Smith  2017-07-26
2      ABT  Abbott Laboratories  1957-03-04
3     ABBV               AbbVie  2012-12-31
4      ACN            Accenture  2011-07-06
..     ...                  ...         ...
498    XYL           Xylem Inc.  2011-11-01
499    YUM          Yum! Brands  1997-10-06
500   ZBRA   Zebra Technologies  2019-12-23
501    ZBH        Zimmer Biomet  2001-08-07
502    ZTS               Zoetis  2013-06-21

[503 rows x 3 columns]

In [50]:
df1['Date added'].dtype

In [51]:
df1['Date'] = pd.to_datetime(df1['Date added'])

In [52]:
df1 =df1.drop(columns='Date added')

In [53]:
df1['Year'] = df1['Date'].dt.year

In [54]:
df1

    Symbol             Security       Date  Year
0      MMM                   3M 1957-03-04  1957
1      AOS          A. O. Smith 2017-07-26  2017
2      ABT  Abbott Laboratories 1957-03-04  1957
3     ABBV               AbbVie 2012-12-31  2012
4      ACN            Accenture 2011-07-06  2011
..     ...                  ...        ...   ...
498    XYL           Xylem Inc. 2011-11-01  2011
499    YUM          Yum! Brands 1997-10-06  1997
500   ZBRA   Zebra Technologies 2019-12-23  2019
501    ZBH        Zimmer Biomet 2001-08-07  2001
502    ZTS               Zoetis 2013-06-21  2013

[503 rows x 4 columns]

In [55]:
# Number of stocks added each year.
yearly_counts = df1['Year'].value_counts().sort_index()

In [56]:
yearly_counts

Year
1957    52
1964     1
1965     2
1969     2
1970     2
1972     2
1973     2
1974     1
1975     2
1976    11
1978     1
1979     1
1980     3
1981     3
1982     5
1983     2
1984     4
1985     7
1986     3
1987     2
1988     4
1989     4
1991     1
1992     2
1993     3
1994     6
1995     7
1996     2
1997    14
1998    11
1999     9
2000     9
2001     8
2002    12
2003     5
2004     6
2005     7
2006     9
2007    11
2008    16
2009    12
2010     8
2011    10
2012    14
2013     9
2014     8
2015    14
2016    21
2017    22
2018    13
2019    21
2020    10
2021    10
2022    15
2023    15
2024    16
2025    18
2026    13
Name: count, dtype: int64

In [69]:
#Maximum number of additions in year from 2020
yearly_counts[(yearly_counts).index > 2020].idxmax()

np.int32(2025)

In [88]:
# Number of companies with atleast 20 years
cutoff = pd.Timestamp.now() - pd.DateOffset(years=20)
stock_20_years = df1[df1['Date'] <= cutoff]

In [89]:
len(stock_20_years)

224